### ISSUE TITLE
Question (probably not issue): Warning: mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.

### ISSUE THREAD

**Issue by cjanow3** [metabolism/wordpress-bundle-demo#3]
Sorry if this is trivial, but I'm having troubling connecting to DB after running 'symfony serve' and navigating to localhost in browser.  I've created .env.local and populated it as instructed.  Am I supposed to create database prior to this step and replace values in .env.local?  Or, is DB supposed to be automatically created after running 'symfony serve'?  I went out on a limb and tried to use doctrine:database as noted in [Symfony documentation](https://symfony.com/doc/current/doctrine.html#configuring-the-database), but Doctrine ORM is not installed for the project.

It has been some time since I've used XAMPP so I may be totally overlooking something...

Please let me know if I should supply other info.

![image](https://user-images.githubusercontent.com/21167198/119869051-6b2f9200-bee5-11eb-99a5-3bcc1e74a1a7.png)

**Comment by jerome-barbato** [comment]
Hi @cjanow3 ! The issue is closed, did you solved it yourself ? 
What was the issue ? 
The database must exists before loading the project, but the message said that the host is unknown

**Comment by cjanow3** [comment]
Hi @wearemetabolism , yes I did get it to work, thank you for quick response.  Problem was within XAMPP, but I managed to figure out config 👍
