### ISSUE TITLE
No route found

### ISSUE THREAD

**Issue by conoralvarez** [metabolism/wordpress-bundle-demo#5]
When the post slug is less than or equal to two characters, no route found will appear, eg:
http://localhost.local/x
http://localhost.local/xy
http://localhost.local/a1
http://localhost.local/1x

If the post slug is chinese, no route found will also appear, eg:
http://localhost.local/标题
http://localhost.local/文字

![image](https://user-images.githubusercontent.com/71684452/133982751-ca1e7a97-d3e2-42fa-b279-c2dc588df028.png)

**Comment by jerome-barbato** [comment]
Hello @conoralvarez , the post slug must be greater than two characters in order to make multilingual website using multisite still working.

 http://localhost.local/fr
 http://localhost.local/en
 http://localhost.local/es
 
 I will try to add a warning on post update
