### ISSUE TITLE
Wordpress installation not triggered

### ISSUE THREAD

**Issue by hackzilla** [metabolism/wordpress-bundle-demo#7]
I've followed the steps in the readme but the Wordpress installation is not triggered.
Therefore Wordpress is dying with no tables in the database.

![Screenshot 2022-01-13 at 17 16 20](https://user-images.githubusercontent.com/1474182/149377739-4d4eebf3-9191-4c54-9d03-23174e892012.png)

**Comment by jerome-barbato** [comment]
Could you please clear your cookie and retry ? This only occur if you were connected to a previous running Wordpress on the same url @hackzilla
